
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int MENOS = 4;
  public static final int MENOR = 19;
  public static final int ELSE = 14;
  public static final int RPAREN = 9;
  public static final int SEMI = 2;
  public static final int WHILE = 15;
  public static final int PONTO_FLUTUANTE = 22;
  public static final int RCURLY = 11;
  public static final int RETURN = 16;
  public static final int IF = 13;
  public static final int LPAREN = 8;
  public static final int ID = 23;
  public static final int ATRIB = 7;
  public static final int VIRGULA = 12;
  public static final int LCURLY = 10;
  public static final int MAIS = 3;
  public static final int IGUAL_IGUAL = 17;
  public static final int EOF = 0;
  public static final int DIFERENTE = 18;
  public static final int DIV = 6;
  public static final int NUMERO = 21;
  public static final int MAIOR = 20;
  public static final int error = 1;
  public static final int VEZES = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "MAIS",
  "MENOS",
  "VEZES",
  "DIV",
  "ATRIB",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "VIRGULA",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAIOR",
  "NUMERO",
  "PONTO_FLUTUANTE",
  "ID"
  };
}

